{{- if .Values.memcached.enabled }}
{{- $fullname := include "sentry.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-memcached
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: ClusterIP
  ports:
    - name: memcached
      port: 11211
      targetPort: memcached
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
{{- end }}
