{{/*
Generates config.yml and sentry.conf.py from the self-hosted examples,
parameterized for the chart's service names + storage backends. Hosts and
secrets are read from env (set in sentry.sentryEnv); chart values drive the
backend selection and public-URL/TLS-aware settings.
*/}}

{{- define "sentry.configyml" -}}
{{- $url := .Values.sentry.system.url -}}
# Generated by sentry-k8s. Loaded as SENTRY_OPTIONS.
system.internal-url-prefix: 'http://{{ include "sentry.fullname" . }}-web:9000'
{{- if $url }}
system.url-prefix: {{ $url | quote }}
{{- end }}

{{- if eq .Values.filestore.backend "s3" }}
filestore.backend: 's3'
filestore.options:
  bucket_name: {{ .Values.filestore.s3.bucketName | quote }}
  {{- if .Values.filestore.s3.endpointUrl }}
  endpoint_url: {{ .Values.filestore.s3.endpointUrl | quote }}
  {{- end }}
  {{- if .Values.filestore.s3.region_name }}
  region_name: {{ .Values.filestore.s3.region_name | quote }}
  {{- end }}
  {{- if .Values.filestore.s3.addressing_style }}
  addressing_style: {{ .Values.filestore.s3.addressing_style | quote }}
  {{- end }}
  {{- if .Values.filestore.s3.signature_version }}
  signature_version: {{ .Values.filestore.s3.signature_version | quote }}
  {{- end }}
  {{- if .Values.filestore.s3.default_acl }}
  default_acl: {{ .Values.filestore.s3.default_acl | quote }}
  {{- end }}
{{- else }}
filestore.backend: 'filesystem'
filestore.options:
  location: {{ .Values.filestore.filesystem.path | quote }}
dsym.cache-path: '/data/dsym-cache'
releasefile.cache-path: '/data/releasefile-cache'
{{- end }}

{{- if eq .Values.filestore.profiles.backend "s3" }}
filestore.profiles-backend: 's3'
filestore.profiles-options:
  bucket_name: {{ .Values.filestore.profiles.s3.bucketName | quote }}
  {{- if .Values.filestore.profiles.s3.endpointUrl }}
  endpoint_url: {{ .Values.filestore.profiles.s3.endpointUrl | quote }}
  {{- end }}
  {{- if .Values.filestore.profiles.s3.region_name }}
  region_name: {{ .Values.filestore.profiles.s3.region_name | quote }}
  {{- end }}
  addressing_style: "path"
  signature_version: "s3v4"
{{- end }}

{{- if .Values.symbolicator.enabled }}
symbolicator.enabled: true
symbolicator.options:
  url: "http://{{ include "sentry.fullname" . }}-symbolicator:3021"
{{- end }}

transaction-events.force-disable-internal-project: true

{{- if .Values.mail.enabled }}
mail.backend: 'smtp'
mail.host: {{ .Values.mail.host | quote }}
mail.port: {{ .Values.mail.port }}
{{- if .Values.mail.username }}
mail.username: {{ .Values.mail.username | quote }}
{{- end }}
mail.use-tls: {{ .Values.mail.useTls }}
mail.use-ssl: {{ .Values.mail.useSsl }}
{{- if .Values.mail.from }}
mail.from: {{ .Values.mail.from | quote }}
{{- end }}
{{- end }}

{{- with .Values.sentry.configYml }}
{{ toYaml . }}
{{- end }}
{{- end -}}


{{- define "sentry.confpy" -}}
{{- $url := .Values.sentry.system.url -}}
{{- $isHttps := and $url (hasPrefix "https://" $url) -}}
# Generated by sentry-k8s.
from sentry.conf.server import *  # NOQA

DATABASES = {
    "default": {
        "ENGINE": "sentry.db.postgres",
        "NAME": env("SENTRY_DB_NAME", "sentry"),
        "USER": env("SENTRY_DB_USER", "postgres"),
        "PASSWORD": env("SENTRY_DB_PASSWORD", ""),
        "HOST": env("SENTRY_POSTGRES_HOST", ""),
        "PORT": env("SENTRY_POSTGRES_PORT", ""),
    }
}

SENTRY_SINGLE_ORGANIZATION = True

SENTRY_OPTIONS["system.event-retention-days"] = int(
    env("SENTRY_EVENT_RETENTION_DAYS", "90")
)

if env("SENTRY_SYSTEM_SECRET_KEY"):
    SENTRY_OPTIONS["system.secret-key"] = env("SENTRY_SYSTEM_SECRET_KEY", "")

SENTRY_SELF_HOSTED_ERRORS_ONLY = {{ .Values.sentry.selfHostedErrorsOnly | ternary "True" "False" }}
SENTRY_AIR_GAP = False

{{- if eq .Values.nodestore.backend "s3" }}

SENTRY_NODESTORE = "sentry_nodestore_s3.S3PassthroughDjangoNodeStorage"
SENTRY_NODESTORE_OPTIONS = {
    "compression": True,
    "endpoint_url": {{ .Values.nodestore.s3.endpointUrl | quote }},
    "bucket_path": "nodestore",
    "bucket_name": {{ .Values.nodestore.s3.bucketName | default "nodestore" | quote }},
    "region_name": {{ .Values.nodestore.s3.region_name | default "auto" | quote }},
}
{{- end }}

SENTRY_OPTIONS["redis.clusters"] = {
    "default": {
        "hosts": {
            0: {
                "host": env("SENTRY_REDIS_HOST", "redis"),
                "password": env("SENTRY_REDIS_PASSWORD", ""),
                "port": env("SENTRY_REDIS_PORT", "6379"),
                "db": "0",
            }
        }
    }
}

CACHES = {
    "default": {
        "BACKEND": "sentry.cache.backends.reconnectingmemcache.ReconnectingMemcache",
        "LOCATION": [env("SENTRY_MEMCACHED_HOST", "memcached:11211")],
        "TIMEOUT": 3600,
        "OPTIONS": {"ignore_exc": True, "reconnect_age": 300},
    }
}
SENTRY_CACHE = "sentry.cache.redis.RedisCache"

DEFAULT_KAFKA_OPTIONS = {
    "bootstrap.servers": env("SENTRY_KAFKA_BOOTSTRAP", "kafka:9092"),
    "message.max.bytes": {{ .Values.kafka.maxMessageBytes | default 50000000 | int64 }},
    "socket.timeout.ms": 1000,
}
SENTRY_EVENTSTREAM = "sentry.eventstream.kafka.KafkaEventStream"
SENTRY_EVENTSTREAM_OPTIONS = {"producer_configuration": DEFAULT_KAFKA_OPTIONS}
KAFKA_CLUSTERS["default"] = DEFAULT_KAFKA_OPTIONS

SENTRY_RATELIMITER = "sentry.ratelimits.redis.RedisRateLimiter"
SENTRY_BUFFER = "sentry.buffer.redis.RedisBuffer"
SENTRY_QUOTAS = "sentry.quotas.redis.RedisQuota"
SENTRY_TSDB = "sentry.tsdb.redissnuba.RedisSnubaTSDB"
SENTRY_SEARCH = "sentry.search.snuba.EventsDatasetSnubaSearchBackend"
SENTRY_SEARCH_OPTIONS = {}
SENTRY_TAGSTORE_OPTIONS = {}
SENTRY_DIGESTS = "sentry.digests.backends.redis.RedisBackend"

SENTRY_WEB_HOST = "0.0.0.0"
SENTRY_WEB_PORT = 9000
SENTRY_WEB_OPTIONS = {
    "http": "%s:%s" % (SENTRY_WEB_HOST, SENTRY_WEB_PORT),
    "protocol": "uwsgi",
    "uwsgi-socket": None,
    "so-keepalive": True,
    "http-keepalive": 15,
    "http-chunked-input": True,
    "workers": {{ .Values.sentry.web.workers | default 3 }},
    "threads": 4,
    "memory-report": False,
    "max-requests": 100000,
    "max-requests-delta": 500,
    "max-worker-lifetime": 86400,
    "thunder-lock": True,
    "log-x-forwarded-for": False,
    "buffer-size": 32768,
    "limit-post": 209715200,
    "disable-logging": True,
    "reload-on-rss": 600,
    "ignore-sigpipe": True,
    "ignore-write-errors": True,
    "disable-write-exception": True,
}

# TLS terminates upstream; the bundled nginx sets X-Forwarded-Proto.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
{{- if $isHttps }}
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
{{- end }}

{{- if $url }}
CSRF_TRUSTED_ORIGINS = [{{ $url | quote }}]
{{- end }}

SENTRY_OPTIONS["mail.list-namespace"] = env("SENTRY_MAIL_HOST", "localhost")
SENTRY_OPTIONS["mail.from"] = f"sentry@{SENTRY_OPTIONS['mail.list-namespace']}"

SENTRY_FEATURES["projects:sample-events"] = False
SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:global-views",
            "organizations:issue-views",
            "organizations:incidents",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:sso-basic",
            "organizations:sso-saml2",
            "organizations:advanced-search",
            "organizations:issue-platform",
            "organizations:monitors",
            "organizations:dashboards-mep",
            "organizations:mep-rollout-flag",
            "organizations:dashboards-rh-widget",
            "organizations:dynamic-sampling",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
            "organizations:performance-view",
            "organizations:session-replay",
            "organizations:user-feedback-ui",
            "organizations:profiling",
            "organizations:profiling-view",
            "organizations:continuous-profiling",
            "organizations:uptime",
            "organizations:uptime-create-issues",
        )
    }
)
{{- range $feature, $enabled := .Values.sentry.features }}
SENTRY_FEATURES[{{ $feature | quote }}] = {{ if $enabled }}True{{ else }}False{{ end }}
{{- end }}

CSP_REPORT_ONLY = True

SENTRY_STATSD_ADDR = env("SENTRY_STATSD_ADDR")
if SENTRY_STATSD_ADDR:
    host, _, port = SENTRY_STATSD_ADDR.partition(":")
    port = int(port or 8125)
    SENTRY_METRICS_BACKEND = "sentry.metrics.statsd.StatsdMetricsBackend"
    SENTRY_METRICS_OPTIONS = {"host": host, "port": port}

{{- if .Values.sentry.config }}

# --- extra raw config (sentry.config) ---
{{ .Values.sentry.config }}
{{- end }}
{{- end -}}
