{{- if .Values.postgresql.enabled }}
{{- $fullname := include "sentry.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-postgresql
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
