{{- if .Values.kafka.enabled }}
{{- $fullname := include "sentry.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-kafka
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 9092
      targetPort: client
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-kafka-headless
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: 9092
      targetPort: client
    - name: controller
      port: 29093
      targetPort: controller
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
{{- end }}
